Personal info details screen
osavchukdoit/AgencyDemoNative pull request #9
Opened 2022-02-22 15:12 UTC by Oleh-Li

please check

2022-02-22 15:20 UTC, osavchukdoit commented on src/components/personalInfoPage/MainPersonalInfo.js
> +        <View style={[styles.titleAndInputWrapper, { marginBottom: 27 }]}>
Lets extract these inline styles to some named style properties.

2022-02-22 15:31 UTC, osavchukdoit requested changes
Pay attention to the comments.

2022-02-22 20:33 UTC, Oleh-Li commented on src/screens/PersonalInfoDetailsScreen.js
> +  wrapper: {
yes, it was redundant

2022-02-22 20:34 UTC, Oleh-Li commented
fixed all in last commit, please check

2022-02-23 07:32 UTC, osavchukdoit approved these changes
Good.

2022-02-23 07:32 UTC, merged